# Generated by Django 4.2.3 on 2023-08-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ttodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2000-08-24'),
            preserve_default=False,
        ),
    ]
